In [0]:
import torch
import numpy as np

data = np.array([1,2,3])

In [131]:
torch.Tensor(data) # class constructor

tensor([1., 2., 3.])

In [132]:
torch.tensor(data) # factory function / constructor, .tensor is the same as .as_tensor(data), from_numpy(data).

tensor([1, 2, 3])

In [133]:
torch.eye(2) # identity function

tensor([[1., 0.],
        [0., 1.]])

In [134]:
torch.zeros(2,2) # create a tensor with all 0s, tensor.ones(x,y) with all 1s, tensor.rand(x,y) with random 0-1.

tensor([[0., 0.],
        [0., 0.]])

In [0]:
t = torch.tensor([
                  [1,1,1,1],
                  [2,2,2,2],            
], dtype = torch.float32)

In [136]:
t.shape

torch.Size([2, 4])

In [137]:
len(t.shape)

2

In [138]:
t = torch.tensor([
                  [
                   [1,2],
                   [2,3],
                   [3,4]               
                   ],
                  [
                   [2,2],
                   [2,3],
                   [3,4,]               
                   ]
], dtype = torch.int)

t.shape
len(t.shape)

3

In [139]:
torch.tensor(t.shape).prod()

tensor(12)

In [140]:
t.numel()

12

In [141]:
t.reshape(4,3)

tensor([[1, 2, 2],
        [3, 3, 4],
        [2, 2, 2],
        [3, 3, 4]], dtype=torch.int32)

In [142]:
t.reshape(1,12)

tensor([[1, 2, 2, 3, 3, 4, 2, 2, 2, 3, 3, 4]], dtype=torch.int32)

In [143]:
t.reshape(12,1)

tensor([[1],
        [2],
        [2],
        [3],
        [3],
        [4],
        [2],
        [2],
        [2],
        [3],
        [3],
        [4]], dtype=torch.int32)

In [144]:
t.reshape(2,6)

tensor([[1, 2, 2, 3, 3, 4],
        [2, 2, 2, 3, 3, 4]], dtype=torch.int32)

In [145]:
t.reshape(2,3,2)

tensor([[[1, 2],
         [2, 3],
         [3, 4]],

        [[2, 2],
         [2, 3],
         [3, 4]]], dtype=torch.int32)

In [146]:
t.reshape(3,2,2)

tensor([[[1, 2],
         [2, 3]],

        [[3, 4],
         [2, 2]],

        [[2, 3],
         [3, 4]]], dtype=torch.int32)

In [147]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

t = torch.ones(3,4)
print(flatten(t))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


## Tensor

* Catenation

In [148]:
t1 = torch.zeros(3,3)
t2 = torch.ones(3,3)

t3 = torch.tensor([[1,2],
                   [3,4]
                   ], dtype = torch.int)
t4 = torch.tensor([[5,2],
                   [3,8]
                   ], dtype = torch.int)

print(torch.cat((t3,t4),dim=0))
print(torch.cat((t3,t4),dim=1))


tensor([[1, 2],
        [3, 4],
        [5, 2],
        [3, 8]], dtype=torch.int32)
tensor([[1, 2, 5, 2],
        [3, 4, 3, 8]], dtype=torch.int32)


Tensor Operations - CNN

In [149]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t = torch.stack((t1, t2, t3))
t.shape

t = t.reshape(3,1,4,4)
t

t[0][0][0]

t


tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [150]:
# t.reshape(1,48)
# x = t.reshape(3,1,2,2,4)
# x.flatten(start_dim=3).shape

t.flatten(start_dim=1)

t



tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

# Tensor Reduction Operations

In [151]:
t = torch.tensor([
                  [1,1,1,1],
                  [3,3,3,3],
                  [5,5,5,5]
                  ], dtype = torch.int)
t.sum()

tensor(36)

In [152]:
t.sum(dim=0)

tensor([9, 9, 9, 9])

In [153]:
t.sum(dim=1)

tensor([ 4, 12, 20])

In [154]:
t.reshape(2,3,2)

tensor([[[1, 1],
         [1, 1],
         [3, 3]],

        [[3, 3],
         [5, 5],
         [5, 5]]], dtype=torch.int32)

In [155]:
# t.reshape(2,3,2).sum(dim=1)
t.reshape(3,2,2).sum(dim=2) == t.reshape(3,2,2).sum(dim=1)

tensor([[True, True],
        [True, True],
        [True, True]])

In [156]:
# t = torch.tensor([
#                   [1,0,0,1],
#                   [3,0,2,1],
#                   [4,3,2,1]
#                   ], dtype = torch.int32)
t = torch.tensor([
                  [1,0,0,6],
                  [0,3,3,0],
                  [4,0,0,5]
                  ], dtype = torch.int32)
t.argmax()

tensor(3)

In [157]:
t.flatten()

tensor([1, 0, 0, 6, 0, 3, 3, 0, 4, 0, 0, 5], dtype=torch.int32)

In [158]:
t.max(dim=0)

torch.return_types.max(values=tensor([4, 3, 3, 6], dtype=torch.int32), indices=tensor([2, 1, 1, 0]))

In [159]:
t.argmax(dim=0)

tensor([2, 1, 1, 0])

In [160]:
t.max(dim=1)

torch.return_types.max(values=tensor([6, 3, 5], dtype=torch.int32), indices=tensor([3, 2, 3]))

In [161]:
t.reshape(2,3,2)

tensor([[[1, 0],
         [0, 6],
         [0, 3]],

        [[3, 0],
         [4, 0],
         [0, 5]]], dtype=torch.int32)

In [162]:
t.reshape(2,3,2).max(dim=0)

torch.return_types.max(values=tensor([[3, 0],
        [4, 6],
        [0, 5]], dtype=torch.int32), indices=tensor([[1, 1],
        [1, 0],
        [1, 1]]))

# Matrix operations

In [0]:
in_features = torch.tensor([1,2,3,4], dtype = torch.float32)

In [0]:
weight_matrix = torch.tensor([
                              [1,2,3,4],
                              [2,3,4,5],
                              [3,4,5,6],
                              [4,5,6,7],
                              [5,6,7,8]
                              ], dtype = torch.float32)

In [165]:
weight_matrix.matmul(in_features)   

tensor([30., 40., 50., 60., 70.])

In [166]:
# explicitly setting the weight matrix of a Linear layer
import torch.nn as nn

fc = nn.Linear(in_features=4, out_features=5, bias = False)
fc.weight = nn.Parameter(weight_matrix)
fc(in_features)

tensor([30., 40., 50., 60., 70.], grad_fn=<SqueezeBackward3>)

y = Ax + b

output = Weight Matrix * Input + bias

[M x Z] = [M x N]*[N x Z] + [M x Z]


# Misc Tensor Operations

In [0]:
# Tensor Concatenations

t1 = torch.tensor([], dtype=torch.int32)
t2 = torch.tensor([1,2,3,4], dtype=torch.int32)

In [168]:
t1

tensor([])

In [169]:
t2

tensor([1, 2, 3, 4], dtype=torch.int32)

In [170]:
torch.cat((t1, t2), dim=0)

RuntimeError: ignored

In [0]:
# Following code will fail because cat only works with equal shape tensors. tensor[2,3] can't fit into tensor[0]
# Use torch.stack to create a new axis and cat to that
# torch.cat((t1.unsqueeze(dim=0), torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)), dim = 1)

In [0]:
# torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32).shape
t1.shape

In [0]:
# Cat on a new axis i.e. do stack manually
t2

In [0]:
t2.unsqueeze(dim=0)

In [0]:
t2.unsqueeze(dim=1)

In [0]:
t3 = torch.tensor([3,3,3,3], dtype=torch.int32)
t4 = t3+1

In [172]:
torch.cat((t1,t2), dim=0)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [188]:
torch.cat((t2.reshape(1,4),t3), dim=0)

RuntimeError: ignored

In [186]:
t2.shape

torch.Size([4])